version: '3.8'
services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: syncblend
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT}:8080"
  vue:
    build: ./front
    ports:
      - "${VUE_PORT}:5173"
    volumes:
      - ./front:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"

  nodejs:
    build: ./back/SyncBlend-websocket
    ports:
      - "${NODEJS_PORT}:${NODEJS_PORT}" # Mapea el puerto 3000 al host
    volumes:
      - ./back/SyncBlend-websocket:/app # Sincroniza tu código fuente con el contenedor
      - /app/node_modules # Asegura que los node_modules no se sobrescriban
    working_dir: /app
    environment:
      NODE_ENV: ${NODE_ENV} # Define el entorno
    restart: always
    command: bash -c "npm install && npm start" # Comando de inicio
    
  laravel:
    build: ./back/SyncBlend-laravel
    ports:
      - "${LARAVEL_PORT}:8000"
    volumes:
      - ./back/SyncBlend-laravel:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    command: bash -c "composer install && php artisan key:generate && php artisan migrate:fresh && php artisan migrate --seed && php artisan serve --host=0.0.0.0"